### ISSUE TITLE
'await using' syntax

### ISSUE THREAD

**Issue by sssarana** [iTwin/itwinjs-core#8198]
I was running into the issue when trying to run a simple iTwin Viewer.
I was following this:
[https://www.itwinjs.org/learning/tutorials/develop-web-viewer/](url)
and nothing else.
I only changed the .env file with appropriate information, however this is what I was getting:

```
ERROR in ./node_modules/@itwin/presentation-frontend/lib/esm/presentation-frontend/selection/SelectionManager.js 364:23
Module parse failed: Unexpected token (364:23)
File was processed with these loaders:
 
./node_modules/source-map-loader/dist/cjs.js
./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|             }
|             const parsedIds = parseIds(ids);
            await using(this._asyncsTracker.trackAsyncTask(), async (_r) => {
|                 switch (ev.type) {
|                     case SelectionSetEventType.Add:
 @ ./node_modules/@itwin/presentation-frontend/lib/esm/presentation-frontend.js 33:0-67 33:0-67
 @ ./node_modules/@itwin/property-grid-react/lib/esm/property-grid-react/hooks/UseContextMenu.js 8:0-85 29:34-64 33:17-57 40:38-73 54:34-64 58:17-57 65:38-76
 @ ./node_modules/@itwin/property-grid-react/lib/esm/property-grid-react.js 18:0-201 18:0-201 18:0-201 18:0-201 18:0-201
 @ ./src/App.tsx 16:0-192 101:10-40 185:13-40 188:69-96 195:59-90 202:60-94
 @ ./src/index.tsx 12:0-24 39:35-38
```

I changed the 'await using' syntax by modifying the SelectionManager.js directly, with the patch attached.

[@itwin+presentation-frontend+4.7.2.patch](https://github.com/user-attachments/files/20662389/%40itwin%2Bpresentation-frontend%2B4.7.2.patch)

This fixed the error. 
However, the `SelectionManager.ts` seems to be already updated similarly, which is why I did not create a PR. This leads to the question: why the issue was happening at the first place?

**Comment by grigasp** [comment]
Clearly the build tool thinks that `using` is not a function but rather the [TS's `using` keyword](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management). Can you check your lockfile and tell:
1. What version of typescript you're using,
2. What version of `@itwin/core-bentley` got resolved as a dependency for `@itwin/presentation-frontend`?

Thanks.

@aruniverse, are there any known issues with viewer on `core @ 4.7`?

**Comment by sssarana** [comment]
Hey, thanks for your reply.

These are the versions:
```json
"typescript": "~5.0.2",
"@itwin/core-bentley": "^4.11.5"
```

**Comment by ben-polinsky** [comment]
`using` support was added in [typescript 5.2.x](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management). Could you upgrade it in your app and try using the un-patched version again?

**Comment by sssarana** [comment]
Unfortunately, I am still getting this error on typescript 5.2.2.

**Comment by aruniverse** [comment]
Just to confirm, what version of `@itwin/presentation-frontend` is resolved by your application? Is it `4.11.5` or `4.7.2`? Please check your `lockfile` for the resolved version, not the `package.json`.

> using support was added in [typescript 5.2.x](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management). Could you upgrade it in your app and try using the un-patched version again?

As per, https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management, have you updated your tsconfig?

_You will also need to set your compilation target to es2022 or below, and configure your lib setting to either include "esnext" or "esnext.disposable"._

```json
{
    "compilerOptions": {
        "target": "es2022",
        "lib": ["es2022", "esnext.disposable", "dom"]
    }
}
```

**Comment by sssarana** [comment]
The resolved versions for `@itwin/presentation-frontend` is `4.7.2`.
I have updated tsconfig, but without the patch I am still getting the same error.

**Comment by grigasp** [comment]
Related: https://github.com/iTwin/viewer/issues/369. I was able to reproduce locally, looking into it now. So far I think the problem is with webpack configuration.

**Comment by grigasp** [comment]
Not webpack configuration, but related to webpack - its dependency `acorn`. See my comment here: https://github.com/iTwin/viewer/pull/370#issuecomment-2979487844

**Comment by pankhur94** [comment]
Fix for this issue is now [merged](https://github.com/iTwin/viewer/pull/370).

If you're unable to create a new app using the updated template, you can apply a workaround by adding the following to your package.json:
```
    "overrides": {
      "acorn": "8.14.0"
    }
```
Then run install again.

**Comment by sssarana** [comment]
Thank you very much all for your help. It works now.
